--liquibase formatted sql
--changeset gabor:6
create table address_aud (id integer not null, rev integer not null, revtype tinyint, city varchar(255), street varchar(255), zipcode varchar(255), primary key (id, rev));
create table address_company_aud (rev integer not null, address_id integer not null, company_id integer not null, revtype tinyint, primary key (rev, address_id, company_id));
create table company_aud (id integer not null, rev integer not null, revtype tinyint, name varchar(255), primary key (id, rev));
create table employee_aud (id integer not null, rev integer not null, revtype tinyint, job varchar(255), name varchar(255), salary double, work_start date, company_id integer, primary key (id, rev));
create table revinfo (rev integer generated by default as identity, revtstmp bigint, primary key (rev));
alter table address_aud add constraint FKcc7vlgg86eqe1dmvivbkv046v foreign key (rev) references revinfo;
alter table address_company_aud add constraint FKj9hn6bu2wprdykc7c4hvugam8 foreign key (rev) references revinfo;
alter table company_aud add constraint FK4bojjw2sh9ku0m2giux40mu3h foreign key (rev) references revinfo;
alter table employee_aud add constraint FK118cwnbfk1ny0ttu4bfqmeh8q foreign key (rev) references revinfo;
